import { JourneyOption, RouteMode, Station } from '../types/transit';

export function calculateJourneyOptions(
  originStation: Station,
  destinationStation: Station,
  intermediateStations: Station[] = []
): JourneyOption[] {
  const distEst = Math.hypot(originStation.lat - destinationStation.lat, originStation.lng - destinationStation.lng) * 110;

  const options: JourneyOption[] = [
    // 1. FASTEST ROUTE (Mo Bus AC Electric Express)
    {
      id: 'opt-fastest',
      title: 'Mo Bus AC Electric Express (Route 10)',
      modeType: 'fastest',
      totalDurationMins: Math.max(16, Math.round(distEst * 2.4)),
      totalFare: 20,
      co2SavingsGrams: 340,
      safetyScore: 94,
      accessibilityScore: 92,
      weatherResilienceScore: 90,
      transfersCount: 0,
      isRecommended: true,
      badges: ['⚡ Fastest Direct Mo Bus', '🔋 100% Electric AC', '🎯 98% On-Time'],
      legs: [
        {
          id: 'leg-f1',
          mode: 'bus',
          lineName: 'Mo Bus 10 (AC Electric Trunk Line)',
          lineCode: 'MB-10',
          color: '#06B6D4',
          fromStation: originStation.name,
          toStation: intermediateStations.length > 0 ? intermediateStations[0].name : destinationStation.name,
          fromCoords: [originStation.lat, originStation.lng],
          toCoords: intermediateStations.length > 0 ? [intermediateStations[0].lat, intermediateStations[0].lng] : [destinationStation.lat, destinationStation.lng],
          durationMins: 16,
          distanceKm: 6.8,
          departureTime: '10:00 AM',
          arrivalTime: '10:16 AM',
          fare: 20,
          co2Grams: 340,
          isStepFree: true,
          safetyScore: 95,
          instructions: [
            `Board Mo Bus 10 (AC Electric) at ${originStation.name} (Bay 1).`,
            `Direct express transit along NH16 corridor with CCTV surveillance.`,
            `Alight safely at ${destinationStation.name}.`,
          ],
        },
      ],
    },

    // 2. CHEAPEST / AFFORDABLE (Ordinary Non-AC Mo Bus 11)
    {
      id: 'opt-cheapest',
      title: 'Mo Bus Standard (Ordinary Line 11)',
      modeType: 'cheapest',
      totalDurationMins: Math.max(22, Math.round(distEst * 3.2)),
      totalFare: 10,
      co2SavingsGrams: 380,
      safetyScore: 88,
      accessibilityScore: 80,
      weatherResilienceScore: 82,
      transfersCount: 0,
      badges: ['💰 Lowest Fare (₹10)', '🎓 50% Student Pass Eligible', '🚍 Direct Route'],
      legs: [
        {
          id: 'leg-c1',
          mode: 'bus',
          lineName: 'Mo Bus Ordinary Non-AC Route 11',
          lineCode: 'MB-11',
          color: '#10B981',
          fromStation: originStation.name,
          toStation: destinationStation.name,
          fromCoords: [originStation.lat, originStation.lng],
          toCoords: [destinationStation.lat, destinationStation.lng],
          durationMins: 22,
          distanceKm: 7.2,
          departureTime: '10:04 AM',
          arrivalTime: '10:26 AM',
          fare: 10,
          co2Grams: 380,
          isStepFree: false,
          safetyScore: 88,
          instructions: [
            `Board Ordinary Non-AC Mo Bus at ${originStation.name}.`,
            `Students with verified DigiLocker ID pay only ₹5.`,
            `Direct drop-off at ${destinationStation.name}.`,
          ],
        },
      ],
    },

    // 3. SENIOR CITIZEN FRIENDLY (Low-Floor Kneeling Bus)
    {
      id: 'opt-senior',
      title: 'Low-Floor Kneeling Accessible Mo Bus',
      modeType: 'senior',
      totalDurationMins: Math.max(18, Math.round(distEst * 2.6)),
      totalFare: 0,
      co2SavingsGrams: 350,
      safetyScore: 99,
      accessibilityScore: 100,
      weatherResilienceScore: 95,
      transfersCount: 0,
      badges: ['🦽 Hydraulic Kneeling Ramp', '👵 Level Boarding Shelter', '💺 Priority Front Seating'],
      legs: [
        {
          id: 'leg-s1',
          mode: 'bus',
          lineName: 'Low-Floor Accessible Mo Bus #10',
          lineCode: 'MB-10',
          color: '#06B6D4',
          fromStation: originStation.name,
          toStation: destinationStation.name,
          fromCoords: [originStation.lat, originStation.lng],
          toCoords: [destinationStation.lat, destinationStation.lng],
          durationMins: 18,
          distanceKm: 6.8,
          departureTime: '10:05 AM',
          arrivalTime: '10:23 AM',
          fare: 0,
          co2Grams: 350,
          isStepFree: true,
          safetyScore: 99,
          instructions: [
            `Conductor deploys level curb ramp for easy step-free entry.`,
            `Reserved front priority seats with wheelchair lock belts.`,
            `Direct stop at main sheltered exit of ${destinationStation.name}.`,
          ],
        },
      ],
    },

    // 4. NIGHT TRAVEL MODE (Women Pink Safe Corridor)
    {
      id: 'opt-night',
      title: 'Women Pink Mo Bus & Night Safe Corridor',
      modeType: 'night',
      totalDurationMins: Math.max(18, Math.round(distEst * 2.5)),
      totalFare: 10,
      co2SavingsGrams: 360,
      safetyScore: 100,
      accessibilityScore: 95,
      weatherResilienceScore: 92,
      transfersCount: 0,
      badges: ['🛡️ 100% CCTV & Security Marshals', '🛡️ Women Pink Mo Bus', '💡 High-Lux Streetlit Route'],
      legs: [
        {
          id: 'leg-n1',
          mode: 'bus',
          lineName: 'Women Pink Safe Mo Bus (Route Pink-1)',
          lineCode: 'PINK-1',
          color: '#EC4899',
          fromStation: originStation.name,
          toStation: destinationStation.name,
          fromCoords: [originStation.lat, originStation.lng],
          toCoords: [destinationStation.lat, destinationStation.lng],
          durationMins: 18,
          distanceKm: 6.8,
          departureTime: '10:10 PM',
          arrivalTime: '10:28 PM',
          fare: 10,
          co2Grams: 360,
          isStepFree: true,
          safetyScore: 100,
          instructions: [
            `Board from designated Women Help Desk illuminated Bay.`,
            `Pink bus staffed with trained security marshals and live dashcams.`,
            `Safe drop-off directly at well-lit police post near ${destinationStation.name}.`,
          ],
        },
      ],
    },

    // 5. ECO-FRIENDLY ROUTE (100% Electric EV Bus)
    {
      id: 'opt-eco',
      title: '100% Electric Zero-Emission Mo Bus',
      modeType: 'eco',
      totalDurationMins: Math.max(16, Math.round(distEst * 2.4)),
      totalFare: 20,
      co2SavingsGrams: 580,
      safetyScore: 94,
      accessibilityScore: 92,
      weatherResilienceScore: 88,
      transfersCount: 0,
      badges: ['🌱 Zero Tailpipe Emissions', '🔋 Lithium Iron Phosphate Battery', '🌳 +580g CO₂ Offset'],
      legs: [
        {
          id: 'leg-e1',
          mode: 'bus',
          lineName: 'Electric Battery Mo Bus EV-402',
          lineCode: 'MB-10',
          color: '#06B6D4',
          fromStation: originStation.name,
          toStation: destinationStation.name,
          fromCoords: [originStation.lat, originStation.lng],
          toCoords: [destinationStation.lat, destinationStation.lng],
          durationMins: 16,
          distanceKm: 6.8,
          departureTime: '10:00 AM',
          arrivalTime: '10:16 AM',
          fare: 20,
          co2Grams: 580,
          isStepFree: true,
          safetyScore: 94,
          instructions: [
            `Electric bus powered by renewable grid charging depot.`,
            `Silent, vibration-free smooth commute saving 580g CO₂.`,
          ],
        },
      ],
    },

    // 6. WEATHER-AWARE / RAIN SAFE (Flyover Bypass)
    {
      id: 'opt-weather',
      title: 'Monsoon Waterlog Bypass via Flyover Corridor',
      modeType: 'weather',
      totalDurationMins: Math.max(20, Math.round(distEst * 2.8)),
      totalFare: 20,
      co2SavingsGrams: 320,
      safetyScore: 96,
      accessibilityScore: 90,
      weatherResilienceScore: 100,
      transfersCount: 0,
      warningMessage: '⛈️ Waterlogging Alert: Jaydev Vihar underpass bypassed via elevated NH flyover.',
      badges: ['☔ Covered Bus Shelters', '🌊 Avoids Flooded Lowlands', '⚡ Storm Resilient'],
      legs: [
        {
          id: 'leg-w1',
          mode: 'bus',
          lineName: 'Mo Bus 10 (Elevated Flyover Reroute)',
          lineCode: 'MB-10',
          color: '#06B6D4',
          fromStation: originStation.name,
          toStation: destinationStation.name,
          fromCoords: [originStation.lat, originStation.lng],
          toCoords: [destinationStation.lat, destinationStation.lng],
          durationMins: 20,
          distanceKm: 7.5,
          departureTime: '10:02 AM',
          arrivalTime: '10:22 AM',
          fare: 20,
          co2Grams: 320,
          isStepFree: true,
          safetyScore: 96,
          instructions: [
            `Mo Bus navigates over dry elevated flyover bridge.`,
            `Completely bypasses inundated road depressions and waterlogged underpasses.`,
            `Arrive directly at covered terminal gate of ${destinationStation.name}.`,
          ],
        },
      ],
    },
  ];

  return options;
}
